### ISSUE TITLE
[...]-code-builder-drush 9.0.2 Not installable or compatible with [...]-code-builder 4.1.5?

### ISSUE THREAD

**Issue by cube-dan** [drupal-code-builder/drupal-code-builder-drush#10]
Greets team Code Builder, 

I'm getting this message when I try to composer require dcbd
```bash
Using version ^9.0 for drupal-code-builder/drupal-code-builder-drush
...[composer junk]
Your requirements could not be resolved to an installable set of packages.

 Problem 1
    - Conclusion: don't install drupal-code-builder/drupal-code-builder-drush 9.0.2
    ... [repeated lines omitted]   
    - Conclusion: remove drupal-code-builder/drupal-code-builder 4.1.5
    - Installation request for drupal-code-builder/drupal-code-builder-drush ^9.0 -> satisfiable by drupal-code-builder/drupal-code-builder-drush[9.0.0, 9.0.0-alpha3, 9.0.1, 9.0.2, 9.x-dev].
    - Conclusion: don't install drupal-code-builder/drupal-code-builder 4.1.5
    - drupal-code-builder/drupal-code-builder-drush 9.x-dev requires drupal-code-builder/drupal-code-builder ^3.2.0 -> satisfiable by drupal-code-builder/drupal-code-builder[3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.22, 3.2.23, 3.2.24, 3.2.25, 3.2.26, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.x-dev, 3.3.0, 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.16, 3.3.17, 3.3.18, 3.3.19, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.3.x-dev].
    - Can only install one of: drupal-code-builder/drupal-code-builder[3.2.0, 4.1.5].
    ... [repeated lines omitted]
    - Can only install one of: drupal-code-builder/drupal-code-builder[3.3.x-dev, 4.1.5].
    - Installation request for drupal-code-builder/drupal-code-builder (locked at 4.1.5) -> satisfiable by drupal-code-builder/drupal-code-builder[4.1.5].
```

It looks like this projects composer file is disallowing the install; [here](https://github.com/drupal-code-builder/drupal-code-builder-drush/blob/9.x/composer.json#L15). Is that the only thing holding up using drupal-code-builder 4.1.5 with drupal-code-builder-drush 9.0.2?

-Dan

**Comment by joachim-n** [comment]
> Is that the only thing holding up using drupal-code-builder 4.1.5 with drupal-code-builder-drush 9.0.2?

No, it's a lot more than that I'm afraid.

drupal-code-builder/drupal-code-builder had a rewrite of its API for version 4. I've not yet had time to update drupal-code-builder/drupal-code-builder-drush for it.

I honestly don't know when I'll get round to it as I don't use the Drush command any more.

I'd be happy to give pointers if you want to try and tackle it.

There are tests in joachim-n/mutable-typed-data which show how Drush should interact with the new API, roughly -- https://github.com/joachim-n/mutable-typed-data/blob/b12b042ef6502cb287794fbab314dee4c161d097/Test/src/DataInteractionTest.php#L267

**Comment by joachim-n** [comment]
Fixed and merged and new release made.
