### ISSUE TITLE
Call to undefined function Drush\Commands\code_builder_commands\drush_set_option()

### ISSUE THREAD

**Issue by byngj123** [drupal-code-builder/drupal-code-builder-drush#11]
Hi,
I am using Drush 10.4.0 with a Drupal 9 site. I just install the drush commands through composer and when I run `drush cbu` i get the following error:
`PHP Fatal error:  Uncaught Error: Call to undefined function Drush\Commands\code_builder_commands\drush_set_option() in /var/www/html/drush/Commands/contrib/code_builder_commands/CodeBuilderCommands.php:73
`
It looks like the drush_set_options() function is no longer a function within Drush 10.
Is there any other alternative for this function?

**Comment by joachim-n** [comment]
Fixes are on branch `sandbox-update-dcb-4.2`, which I need to clean up and merge to main.

**Comment by joachim-n** [comment]
Fixed and merged and new release made.
