### ISSUE TITLE
Wondering about file permissions

### ISSUE THREAD

**Issue by jurgenhaas** [drupal-code-builder/drupal-code-builder-drush#9]
In my development environment I do have a file mask such that new files are writeable by the owner and the group. However, when I use `drush gen` the new files are always only writeable by the owner but not by the group. Is the code generator deliberately setting it that way or is there anything I can do to get that changed?

**Comment by joachim-n** [comment]
`drush gen` isn't this project, it's the code generator that's bundled with Drush 9.

(FWIW, this project's Drush command uses a plain old file_put_contents().)

**Comment by jurgenhaas** [comment]
So where do I find the right issue queue for that other project then? Any hint is much appreciated.
